;;   -*- lexical-binding: t; -*-
;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        backward-sexp
        delete-horizontal-space
        electric-newline-and-maybe-indent
        kill-region
        mark-sexp
        mc/mark-next-lines
        org-beginning-of-line
        org-delete-char
        org-end-of-line
        org-self-insert-command
        pulsar-pulse-line-magenta
        ))

(setq mc/cmds-to-run-once
      '(
        mc/mark-previous-lines
        multiple-cursors-mode
        ))
