exec-once = qs -c noctalia-shell
exec-once = gnome-keyring-daemon --start --components=secrets
exec-once = systemctl --user start hyprpolkitagent
exec-once = dbus-update-activation-environment --all
exec-once = dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
exec-once = systemctl --user import-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
exec-once = wl-paste --watch cliphist store
exec-once = hyprpm reload
exec-once = /home/stradlater/LibreWebTools/TgWsProxy_linux_amd64
