exec-once = qs -c "noctalia-shell" &
exec-once = gnome-keyring-daemon --start --components=secrets
exec-once = hypridle
exec-once = systemctl --user start hyprpolkitagent
exec-once = dbus-update-activation-environment --all
exec-once = dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
exec-once = systemctl --user import-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
exec-once = hyprpm reload



