source = ~/.config/hypr/extra/vars.conf

$MOD = SUPER
$HYPR = Hyper_L



bind = $MOD, RETURN, exec, $terminal
bind = $MOD, Z, killactive,
bind = $MOD, M, exit,
bind = $MOD, E, exec, $fileManager
bind = $MOD, V, togglefloating,
bind = $MOD, SPACE, exec, $launcher
bind = $MOD, P, pseudo,
bind = $MOD SHIFT, J, togglesplit,
bind = $MOD SHIFT, P, exec, hyprpicker -a
bind = $MOD SHIFT, L, exec, qs -c noctalia-shell ipc call lockScreen lock
bind = $MOD SHIFT, S, exec, hyprshot -m region --clipboard-only

bind = $MOD, h, movefocus, l
bind = $MOD, l, movefocus, r
bind = $MOD, k, movefocus, u
bind = $MOD, j, movefocus, d

bind = $MOD,	TAB,	workspace, previous
bind = $MOD,	1, 	split-workspace, 1
bind = $MOD,	2, 	split-workspace, 2
bind = $MOD,	3, 	split-workspace, 3
bind = $MOD,	4, 	split-workspace, 4
bind = $MOD,	5, 	split-workspace, 5
bind = $MOD,	6, 	split-workspace, 6
bind = $MOD,	7, 	split-workspace, 7
bind = $MOD,	8,	split-workspace, 8
bind = $MOD,	9, 	split-workspace, 9
bind = $MOD,	0,	split-workspace, 10

bind = $MOD SHIFT, 1, split-movetoworkspace, 1
bind = $MOD SHIFT, 2, split-movetoworkspace, 2
bind = $MOD SHIFT, 3, split-movetoworkspace, 3
bind = $MOD SHIFT, 4, split-movetoworkspace, 4
bind = $MOD SHIFT, 5, split-movetoworkspace, 5
bind = $MOD SHIFT, 6, split-movetoworkspace, 6
bind = $MOD SHIFT, 7, split-movetoworkspace, 7
bind = $MOD SHIFT, 8, split-movetoworkspace, 8
bind = $MOD SHIFT, 9, split-movetoworkspace, 9
bind = $MOD SHIFT, 0, split-movetoworkspace, 10

bind = $MOD ALT, l, workspace, +1
bind = $MOD ALT, h, workspace, -1

bind = $MOD, S, togglespecialworkspace, magic
bind = $MOD SHIFT, X, movetoworkspace, special:magic

bind = $MOD, mouse_up, workspace, +1
bind = $MOD, mouse_down, workspace, -1

bindm = $MOD, mouse:272, movewindow
bindm = $MOD, mouse:273, resizewindow

bindl = ,	XF86Tools, exec, echo 'VCD_TOGGLE_SELF_MUTE' >> $XDG_RUNTIME_DIR/vesktop-ipc
bindl = $MOD,	XF86Tools, exec, echo 'VCD_TOGGLE_SELF_DEAF' >> $XDG_RUNTIME_DIR/vesktop-ipc

bindel = ,XF86AudioRaiseVolume,	exec, wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%+ -l 1.0
bindel = ,XF86AudioLowerVolume, exec, wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%- -l 1.0
bindel = ,XF86AudioMute,	exec, wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle
bindel = ,XF86AudioMicMute,	exec, wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle
bindel = ,XF86MonBrightnessUp,	exec, lightctl up
bindel = ,XF86MonBrightnessDown,exec, lightctl down

#Music controls
bindl = , XF86AudioNext, exec,	playerctl next
bindl = , XF86AudioPause, exec,	playerctl play-pause
bindl = , XF86AudioPlay, exec,	playerctl play-pause
bindl = , XF86AudioPrev, exec,	playerctl previous

bindsl = Alt_R, slash,		exec, playerctl play-pause 
bindsl = Alt_R, comma,		exec, playerctl previous
bindsl = Alt_R, period,		exec, playerctl next
bindsl = Alt_R, bracketright,	exec, wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%+ -l 1.0
bindsl = Alt_R, apostrophe,	exec, wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%- -l 1.0
